#! /usr/bin/python
# -*- coding: utf-8 -*-

import sys
import os

BASE_DIR = os.path.abspath( os.path.join( os.path.dirname( __file__ ), ".." ) )
path     = os.path.abspath( os.path.join( BASE_DIR, "python" ) )
sys.path.append( path )

import momo
import numpy as np

def split_line( line ):
  v = line.split()
  return [
    int( float( v[0] ) ), float( v[1] ), int( float( v[2] ) ), 
    float( v[3] ), float( v[4] )
  ]

def read_data( filename ):
  f = open( filename )
  data = [split_line( l ) for l in f]
  f.close()
  return data

data = [d for d in read_data( sys.argv[1] ) if abs( d[3] ) < 10.5]

lastid = 0
ids  = {}
last = {}
result = []

for d in data:
  if not d[2] in ids or d[0] - last[d[2]] > 1:
    ids[d[2]] = lastid
    lastid += 1
  last[d[2]] = d[0]
  d[2] = ids[d[2]]
  result.append( d )

f = open( "data/tracks/%s.txt" % sys.argv[2], "w" )
for d in data:
  f.write( "%i %f %i %f %f\n" % ( d[0], d[1], d[2], d[3], d[4] ) )
f.close()


